---
classname: AGRON 590RD - R for Data Science  
semester: Spring 2018
time: T 2:10-3:00
room: Agronomy G541
website: http://agron590rd.trydiscourse.com 
instructor:
 - name: "Ranae Dietzel"
   email: rdietzel@iastate.edu
   office: 3403 Agronomy Hall
oh_time: By appointment
oh_office: Agronomy 3403
output:
  pdf_document:
    template: syllabus-template.tex
---
#Class Format
We will follow a flipped-classroom approach where students are responsible for reading assigned materials outside of class and practicing new methods by actively coding in the classroom. 


#Textbook:
- Grolemund, Garrett, and Hadley Wickham. *R for Data Science*. O'Reilly, 2017. http://r4ds.had.co.nz


#Course Objectives  
This course will closely follow the textbook *R for Data Science* with the objectives of introducing students to the R language through methods meant for R beginners or those not needing an in-depth understanding of the language. Students will learn data visualization, transformation, and analysis as well as how to move data around into workable structures. We will cover basic R programming and modeling and great ways to become better at data organization and communicating results. 


#Tentative Course Outline:

1. Introduction, Context, and Set-up \dotfill Week 1
1. R4DS Section 1-3.4 Intro and Data Viz \dotfill Week 2-3
1. R4DS Section 3.4-3.10 Data Viz \dotfill Week 4-5
1. R4DS Section 4 -5 Basics and Transformations  \dotfill Week 6-7
1. R4DS Section 7 EDA \dotfill Week 7-9
1. R4DS Section 8,9,10 Projects and Tibbles \dotfill Week 10
1. R4DS Section 11 Data Import  \dotfill Week 11
1. R4DS Section 12 Tidy Data \dotfill Week 12
1. R4DS Section 14-15 Strings \dotfill Week 13
1. R4DS Section 16 Dates and Times \dotfill Week 14
1. R4DS Section 17-18 Programming and Pipes \dotfill Week 15

#Assessment: 

A 1-credit lecture course requires 50 minutes in the classroom and 2 hours outside of the classroom. Weeks will be designed to include ~2 hours of reading and practice outside of the classroom and 50 minutes of actively writing code in the classroom. Assessment will be based on attendance and participation. 

##Attendance 
I have found that research schedule demands of graduate school are a real impediment to learning new skills and taking non-required courses. This course will aim to keep a flexible attendance policy. However, inability to attend a class must be made up with in-kind time. Instructor and student must agree on what makes up for a class absence, which will be dependent upon the week.   

##Participation 
Participation will occur through working on exercises during class time. If required reading is not performed, it will not be possible to work on the exercises during the short, 50 min period. Code produced during class will be turned in at the end of each class and degree of participation will be determined.  